# Generated by Django 5.0.6 on 2024-05-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
