# Generated by Django 5.0.6 on 2024-05-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
